version: '3'

services:
  eqdkp:
    build: .
    container_name: eqdkp-web
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - DOMAIN_NAME=${DOMAIN_NAME}
    restart: always
    depends_on:
      - db
      - certbot
    volumes:
      - eqdkp-data:/var/www/html
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    networks:
      - eqdkp-network

  db:
    image: mysql:5.7
    container_name: eqdkp-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}    
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - eqdkp-network

  certbot:
    image: certbot/certbot
    container_name: eqdkp-certbot
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done"

volumes:
  db_data:
  eqdkp-data:
  certbot-conf:
  certbot-www:

networks:
  eqdkp-network:

