version: '3'

services:
  eqdkp:
    build: .
    container_name: eqdkp-web
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - DOMAIN_NAME=${DOMAIN_NAME}
    restart: always
    depends_on:
      - db
    volumes:
      - eqdkp-data:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt  # Mount for SSL certificates

    networks:
      - eqdkp-network

  db:
    image: mysql:5.7
    container_name: eqdkp-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}    
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - eqdkp-network

volumes:
  db_data:
  eqdkp-data:


networks:
  eqdkp-network:

