version: '3'

services:
  web:
    build: .
    container_name: my-web-container
    ports:
      - "80:80"
    environment:
      - DEBIAN_FRONTEND=noninteractive
    restart: always
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: eqdkp
      MYSQL_USER: eqdkpuser
      MYSQL_PASSWORD: eqdkppassword        
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
